### ISSUE TITLE
Daemon does not work on Raspbian Jessie

### ISSUE THREAD

**Issue by denics** [denics/yatse-kodi-startup#2]
Since last update to Raspbian Jessie, Yatse-kodi startup does not work properly. Here is the log:

```
2016-01-10 23:05:05 Kodi wake up from Yatse
2016-01-10 23:05:05 ©2015 - Denis Pitzalis
2016-01-10 23:05:05 Wait 10 seconds before doing anything
2016-01-10 23:05:15 Waiting for a signal from Yatse remote on port 9
2016-01-10 23:05:24 Yatse calling

2016-01-10 23:05:24 Yatse starting kodi: YatseStart-Xbmc
2016-01-10 23:05:30 Yatse calling

2016-01-10 23:05:30 Yatse starting kodi: YatseStart-Xbmc
2016-01-10 23:07:08 Yatse calling

2016-01-10 23:07:08 Yatse starting kodi: YatseStart-Xbmc
2016-01-10 23:07:10 Yatse calling

2016-01-10 23:07:10 Yatse starting kodi: YatseStart-Xbmc
2016-01-10 23:07:11 Yatse calling

2016-01-10 23:07:11 Yatse starting kodi: YatseStart-Xbmc
```

**Comment by ghost** [comment]
Hi, any luck coming up with a solution for Jessie?

**Comment by denics** [comment]
Hi @tomlyl,
can you please try to reinstall libfile-pid-perl, once I did that it worked for me, so if you could confirm it would be great.

**Comment by pcmedicjax** [comment]
I tried that but it did not help 

```
On Friday, January 22, 2016 7:18 AM, Denix <notifications@github.com> wrote:
```

 Hi @tomlyl,
can you please try to reinstall libfile-pid-perl, once I did that it worked for me, so if you could confirm it would be great.—

**Comment by ghost** [comment]
For now I just copied the files and executed the commands from "ReadMe" section. Unfortunately, I get this message:
Failed to start yatse.service: Unit yatse.service failed to load: No such file or directory.
EDIT
I managed to get servic active, but it doesn't start Kodi when I send WOLs from my HTC.

**Comment by danifr** [comment]
Hi all,

I wrote my own version of this in python v3. It works fine with systemd based operating systems.
If there is some interest and @denics agrees, I can upload my code :)

Cheers,
Daniel.

**Comment by denics** [comment]
Hi @danifr,
This is a great news! Thanks! I propose to move my Perl version to a Perl branch, and make your Python the master version. What do you think?

**Comment by denics** [comment]
Or, even better, rename it in a more generic form, like remote-kodi-startup and make sure all (or most of them) remotes wol are supported, in the hope one day of being included in some distro 😊

**Comment by ghost** [comment]
Hey, @danifr it seems like you've just done the work I was about do get down to :smile: 
It would be great if you could share your code. I really hope it would work in my case too.

**Comment by pcmedicjax** [comment]
How can I get any version that works on a RPI2 running Jessie.

**Comment by ghost** [comment]
For now, we shall wait for Daniel to share the code. I hope he will.

2016-01-26 22:38 GMT+01:00 pcmedicjax notifications@github.com:

**Comment by danifr** [comment]
Hi guys,

sorry for the delay but I realized I needed to rewrite the README :D everything should be in place now.
You can find the code here: https://github.com/danifr/wol-kodi/tree/python (for now it has its own branch "python")
It's pretty much the same I'm using on my Pi with Archlinux.

Please test it out on Jessie and let me know if I need to modify something.
Cheers!
Daniel.

**Comment by ghost** [comment]
I don't know why, but I get an error trying to start a service. My complete log looks like that:

pi@raspberrypi:/usr/lib/systemd/scripts/wolkodi $ sudo systemctl status wolkodi.service -l
● wolkodi.service - Kodi Remote Start
   Loaded: loaded (/usr/lib/systemd/system/wolkodi.service; disabled)
   Active: failed (Result: exit-code) since śro 2016-01-27 16:43:38 CET; 39s ago
  Process: 9029 ExecStart=/usr/bin/python /usr/lib/systemd/scripts/wolkodi (code=exited, status=1/FAILURE)
 Main PID: 9029 (code=exited, status=1/FAILURE)

sty 27 16:43:38 raspberrypi python[9029]: /usr/bin/python: can't find '**main**' module in '/usr/lib/systemd/scripts/wolkodi'
sty 27 16:43:38 raspberrypi systemd[1]: wolkodi.service: main process exited, code=exited, status=1/FAILURE
sty 27 16:43:38 raspberrypi systemd[1]: Failed to start Kodi Remote Start.
sty 27 16:43:38 raspberrypi systemd[1]: Unit wolkodi.service entered failed state.

**Comment by danifr** [comment]
What if you just try to execute the script from the command line?

```
sudo python /usr/lib/systemd/scripts/wolkodi
```

What version of python are you using?

**Comment by ghost** [comment]
I figured it out. Something was messed up with the path to the file. Now I sort of managed to start the kodi using Yatse, but I had to delete the IF-statement in your code. Moreover, it seems to be the difference between starting Kodi as Pi and as root.

**Comment by denics** [comment]
hei @danifr does it work also with kodi remote control? I will add a link to your version in my README.md file. - yes, it works :) great job!

**Comment by danifr** [comment]
I updated my code a little bit to support Raspbian (Jessie) with no changes from the user.
I'm not particularly proud of this patch but it does its job.

You can find the code here: https://github.com/danifr/wol-kodi/blob/python/wolkodi.py

:)

**Comment by pcmedicjax** [comment]
Ok I seem to have the python version running but now my rpi is not booting to the desktop.
Here is my goal.
I need my RPI to boot to a desktop and run kodi  When needed with a remote or mouse click and be able to exit back to the desk top to run other apps ie: a browser or game emulator or any other apps.

What am I doing Wrong?

**Comment by danifr** [comment]
Hi,

I installed Raspbian Jessie just to test my code and it works as expected.
Anyway I made some changes (again) and now it should work better.

I can confirm that it works fine with Raspbian and Archlinux.

@pcmedicjax, about your use case:
Apparently is not possible https://forum.htpcguides.com/Thread-SOLVED-kodi-shutdown-menu-raspbian-jessie
Perhaps you could write some code to check if kodi is running or not, if not Xs must be running.

**Comment by denics** [comment]
Thanks @danifr for your code: https://github.com/danifr/wol-kodi/tree/python !
